title: Investment & trading
description: "Bitcashew00 \U0001F6E1ï¸ now has the reason to start educating it's visitors on how to invest and also earn as an investor, who could also aquire professional development for free legal action"
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
